# Generated by Django 3.1.5 on 2021-01-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.FileField(upload_to='')),
                ('package_name', models.CharField(max_length=127)),
                ('package_version_code', models.CharField(max_length=20)),
            ],
        ),
    ]
